[tools]
go = "1.23"

[env]
BIN="asciiban"

[tasks.build]
alias = "b"
run = "go build -o ./bin/${BIN}"

[tasks.generate]
alias = "g"
run = "go generate ./..."

[tasks.output_readme_screens]
depends = ["b"]
alias = "ors"
run = """
bin/${BIN} "america" -p patriot -f dosrebel
bin/${BIN} "what is real?" -p matrix -f georgia11
bin/${BIN} "Google" -p google -f univers
bin/${BIN} "Good yard" -f crazy -p retro
"""
